[package]
name = "sacn"
description = "Rust sACN implementation."
version = "0.1.0"
authors = ["Lukas Schmierer <lukas.schmierer@lschmierer.de>"]
documentation = "http://lschmierer.github.io/sacn/"
repository = "https://github.com/lschmierer/sacn"
license = "MIT OR Apache-2.0"

[dependencies]
net2 = "*"
uuid = "*"
